name: Test Suite
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    runs-on: buildjet-4vcpu-ubuntu-2204
    name: Test
    steps:
      
- uses: buildjet/cache@v3
  with:
    path: ~/.npm
    id: npm-cache
    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    restore-keys: |
      ${{ runner.os }}-node-
- name: Download dependencies
  if: steps.npm-cache.outputs.cache-hit != 'true'
  run: npm c
